### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by makwanaajay** [astorm/pestle#120]
I have tried pestle but I am not able to work with it.
When tried to run command "pestle.phar list", it gives me the error "pestle.phar : command not found"

**Comment by astorm** [comment]
@makwanaajay Oh no!  That's no good.  Does the same thing happen if you type

```
pestle.phar help
```

If so, what's the result when you type

```
php -v
```

**Comment by makwanaajay** [comment]
It show me below.
PHP 5.6.18 (cli) (built: Feb  4 2016 22:08:11) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by makwanaajay** [comment]
when i try to list the command or any other command with pestle I think it tries to open the pestle file.

**Comment by astorm** [comment]
@makwanaajay I'm rereading your issue here, and I think I may have misunderstood your problem.  Were your having a problem with `list` as described here?  https://github.com/astorm/pestle/issues/121

Or were you having a problem with running **any** pestle command?

If the later, where did you download `pestle.phar` to?  If you run `pestle.phar` by itself with no arguments what happens?  What about running `php /path/to/your/downloaded/pestle.phar`?

**Comment by astorm** [comment]
@makwanaajay Not sure if this is still a problem -- if it is please reopen and let us know!

**Comment by codelogn** [comment]
I am having same issue. **php pestle.phar** works. Only **pestle.phar** does not.

php -v

PHP 5.6.25-2+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

**Comment by astorm** [comment]
@mdrobiul Could you copy/paste the terminal output when you type `pestle.phar`?

**Comment by codelogn** [comment]
vagrant@precise32:~/test_pestle$ pestle.phar
pestle.phar: command not found

**Comment by codelogn** [comment]
I don't know if it helps. On same box,  n98-magerun.phar and composer.phar works fine without php. Then I moved pestle.phar too to /usr/local/bin/ since that's where magerun and composer live. If I run pestle.phar in there without php, then I receive following message:
vagrant@precise32:/usr/local/bin$  pestle.phar
bash: /usr/bin/pestle.phar: No such file or directory

**Comment by astorm** [comment]
What happens if you try to run it directly from /usr/local/bin/ -- i.e.

    $ /usr/local/bin/pestle.phar

**Comment by codelogn** [comment]
Here is the output:

```
vagrant@precise32:/usr/local/bin$ /usr/local/bin/pestle.phar
PHP Warning:  require_once(phar:///home/vagrant/test_pestle/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php): failed to open stream: phar error: invalid url or non-existent phar "phar:///home/vagrant/test_pestle/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php" in phar:///usr/local/bin/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 124
PHP Fatal error:  require_once(): Failed opening required 'phar:///home/vagrant/test_pestle/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php' (include_path='phar:///usr/local/bin/pestle.phar/vendor/phing/phing/classes:.:/usr/share/php') in phar:///usr/local/bin/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 124

```

Also note that there is some cache. I have removed test_pestle directory from my home directory. Why is it still trying to load from test_pestle?

**Comment by astorm** [comment]
@mdrobiul Yeah, there's def. some weirdness going on.  That's not standard behavior. How did you get your copy of pestle?  How did it get into your VM?

**Comment by codelogn** [comment]
At the beginning, I ran curl -LO http://pestle.pulsestorm.net/pestle.phar in my home directory/test-folder. Then I deleted this directory and reran the download command inside /usr/local/bin because I thought that might take care of the cache issue. I also restarted my apache bunch of times for fixing the cache issue. That did not help.

**Comment by astorm** [comment]
> might take care of the cache issue

Have you tried deleting the pestle_cache folder at

    /tmp/pestle_cache

**Comment by codelogn** [comment]
No, I just removed cache. Inside /usr/local/bin, pestle.phar works without php. 

Also, now anywhere /usr/local/bin/pestle.phar works without php.

**Comment by astorm** [comment]
@mdrobiul (or anyone else) -- I think we're good here?  Closing out -- if we're not good re-open or open a new issue.  Thanks all!

**Comment by twosg** [comment]
Had the same problem with current version, just for info.

Is it possible to composer require pestle.phar to the magento root directly and use the /Magento/var/tmp folder instead?

**Comment by astorm** [comment]
@twosg Sorry to hear about your trouble!  If you have a moment, we have a few questions about the problem you ran into.

Are you saying you say a 
> pestle.phar : command not found

and that removing `/tmp/pestle_cache` cleared things up for you?  Or did you have only some of that happen?

Also, we're not sure that you mean by 

> Is it possible to composer require pestle.phar to the magento root directly and use the /Magento/var/tmp folder instead?

Are you suggesting that pestle be pulled into a Magento project's `compose.json` file, ran from `vendor/bin`, and that it should use `/Magento/var/tmp` as its temporary cache folder?  Or something else?

**Comment by twosg** [comment]
@astorm Hey, 

I meant that I had this error:
```
sven@SG-MINT18 ~/PROJEKTE/Domains/domain-magento2 $ php pestle.phar 
PHP Warning:  require_once(phar:///home/sven/PROJEKTE/Domains/domain.de-m2/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php): failed to open stream: phar error: invalid url or non-existent phar "phar:///home/sven/PROJEKTE/Domains/domain.de-m2/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php" in phar:///home/sven/PROJEKTE/Domains/domain-magento2/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 136
PHP Fatal error:  require_once(): Failed opening required 'phar:///home/sven/PROJEKTE/Domains/domain.de-m2/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php' (include_path='phar:///home/sven/PROJEKTE/Domains/domain-magento2/pestle.phar/vendor/phing/phing/classes:.:/usr/share/php') in phar:///home/sven/PROJEKTE/Domains/domain-magento2/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 136
```
The pathes are wrong, cached version uses the path from one project (where pestle was used), although I was executing pestle in another project dir. Removing `/tmp/pestle_cache` solved it for me.

> Are you suggesting that pestle be pulled into a Magento project's compose.json file, ran from vendor/bin, and that it should use /Magento/var/tmp as its temporary cache folder?

Basically yes :) Or was I using pestle in a wrong way?

**Comment by twosg** [comment]
I just discovered `How to Use Pestle Code in your Application` section of the readme, but install fails with 
```
sven@SG-MINT18 ~/project-dir $ composer require pulsestorm/pestle
Using version ^1.4 for pulsestorm/pestle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for fzaninotto/faker == 1.7.1.0 -> satisfiable by fzaninotto/faker[v1.7.1].
    - pulsestorm/pestle 1.4.0 requires fzaninotto/faker 1.6.0 -> satisfiable by fzaninotto/faker[v1.6.0].
    - pulsestorm/pestle 1.4.1 requires fzaninotto/faker 1.6.0 -> satisfiable by fzaninotto/faker[v1.6.0].
    - pulsestorm/pestle 1.4.2 requires fzaninotto/faker 1.6.0 -> satisfiable by fzaninotto/faker[v1.6.0].
    - Conclusion: don't install fzaninotto/faker v1.6.0
    - Installation request for pulsestorm/pestle ^1.4 -> satisfiable by pulsestorm/pestle[1.4.0, 1.4.1, 1.4.2].
Installation failed, reverting ./composer.json to its original content.
```

**Comment by astorm** [comment]
@twosg 

> Basically yes :) Or was I using pestle in a wrong way?

So, there's multiple ways to use this project.  From one point of view, the purpose of this project is  to generate a [stand alone `.phar`](http://pestle.pulsestorm.net/pestle.phar
) file that contains all the commands (including the Magento code generating command) that you can run via pestle.  To use this phar you don't need to repo -- you can just [grab the phar](http://pestle.pulsestorm.net/pestle.phar) and you're off to the races.

The second way to use this repo is if you want to contribute to pestle development.

The third way is if you want to use a pestle function in your own project (which is currently achieved via a big generated include file, but eventually/ideally we'll have a `pestle_import` that works in any enviornment.  This is a stretch goal).

So, based on your second comment, it sounds like you tried to include this project as a composer dependency, but our hard coded 1.6.0  `fzaninotto/faker` module interfered with your project's `fzaninotto/faker:1.7.1` module.  We opened a ticket for this: https://github.com/astorm/pestle/issues/321

Based on your first comment you ran into a problem trying to use the (or a self generated?) pestle phar file in two different projects.  We opened an individual ticket for that as well: https://github.com/astorm/pestle/issues/320

We still need some clarifying information, but we'll ask those questions in those ticket.  Re-closing this particular issue, as these are new issues.
