### ISSUE TITLE
List Command not Wokring

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#121]
$ pestle.phar list
Can't find [list] in Pulsestorm\Pestle\Runner\includeLibraryForCommand

**Comment by ddoddsr** [comment]
looks like at some point _list_ was changed to _list_commands_, 
but still some tutorials have
`php pestle.phar list`  
http://alanstorm.com/magento2_pestle_code_generation
and in the READ.md  in https://github.com/astorm/pestle

**Comment by astorm** [comment]
D'oh!  Thanks @ddoddsr -- I can't remember the context of that change, but it was a good excuse to introduce the bones for a simple command aliasing feature.  The `list` commands should work again.  Closing for now, please reopen if anyone's having issues with the latest `phar`

**Comment by PascalBrouwers** [comment]
Had this issue with the current version. list_commands works fine btw.

**Comment by astorm** [comment]
Thanks for the heads up @PascalBrouwers  -- I think this regression has to do with our recent change from underscores (`list_commands`) to dashes (`list-commands`).  Pestle's supposed to check for both versions of a command -- but it sounds like it doesn't.  Will investigate for the next release.

**Comment by theycallmepepper** [comment]
@astorm You're right and adjusting `modules/pulsestorm/pestle/runner/module.php` Line 213 to             `return 'list-commands'; `and rebuilding corrects the issue.  What is your process for PRs?  I've been using this a bit so I could try to contribute in my free time.

**Comment by astorm** [comment]
@theycallmepepper just issue a pull request against master, and if it passes the travis build I'll usually accept, or give you feedback on why something isn't acceptable.

**Comment by astorm** [comment]
Fixed in master, will go live with next point release.
