### ISSUE TITLE
generate_crud_model is gone

### ISSUE THREAD

**Issue by dio5** [astorm/pestle#124]
Just updated my pestle version and suddenly this was gone?

**Comment by astorm** [comment]
@dio5 Thank you for the feedback, and apologies for the bug. Something something early days. 

Can you paste the output of `pestle.phar list_commands` here so we can see which commands **are** listed?

**Comment by dio5** [comment]
Hi Alan,

Sure, but the list is quite extensive. 

If I look in pestle.phar/modules/pulsestorm/magento2/cli/generate I can see that crud/model dir is gone now. (While it was there on my older version)

By the way, also generate_observer seems broken and generates a fatal error. I'll open a new ticket for that with the output of the error.

Thanks for the great tool by the way.

**Comment by astorm** [comment]
Hmm, @dio5 -- what tool are you using to examine the `phar` file?  Also, how did you update it? (downloading a new version? building a new version?)

**Comment by dio5** [comment]
I just removed it and reinstalled with curl as on the readme

curl -LO http://pestle.pulsestorm.net/pestle.phar

Re examining, just looking at it with phpstorm in my project.

**Comment by dio5** [comment]
Wow, hang on there... I think I did

curl -LO http://alanstorm.com/2016/projects/pestle/pestle.phar 

and that one gave me the one without crud.... I just did it with pulsestorm and crud is back.

I have no idea where I got the alanstorm link from though?

**Comment by dio5** [comment]
Ah, got the alan storm link from the wiki!

https://github.com/astorm/pestle/wiki/Using-Pestle

**Comment by astorm** [comment]
D'oh!  We'll make sure the "keeping the wiki up to date" department suffers for this.  

Wiki's been updated with the real URL, apologies for the confusion, and thanks for helping this project get a little bit better.
