### ISSUE TITLE
generate_observer is broken

### ISSUE THREAD

**Issue by dio5** [astorm/pestle#125]
$ php pestle.phar generate_observer  
Full Module Name? (Pulsestorm_Generate)] 
Event Name? (controller_action_predispatch)] 
Observer Name? (pulsestorm_generate_listener)] 
Class Name? (Pulsestorm\Generate\Model\Observer)] 
PHP Fatal error:  Call to undefined function Pulsestorm\Magento2\Cli\Library\addSchemaToXmlString() in phar:///home/dio5/www/site/mage2local/pestle.phar/modules/pulsestorm/magento2/cli/library/module.php on line 92
PHP Stack trace:
PHP   1. {main}() /home/dio5/www/site/mage2local/pestle.phar:0
PHP   2. main() /home/dio5/www/site/mage2local/pestle.phar:9
PHP   3. Pulsestorm\Pestle\Runner\main() /home/dio5/www/site/mage2local/pestle.phar:7
PHP   4. ReflectionFunction->invokeArgs() phar:///home/dio5/www/site/mage2local/pestle.phar/modules/pulsestorm/pestle/runner/module.php:333
PHP   5. Pulsestorm\Magento2\Cli\Generate\Observer\pestle_cli() phar:///home/dio5/www/site/mage2local/pestle.phar/modules/pulsestorm/pestle/runner/module.php:333
PHP   6. initilizeModuleConfig() phar:///home/dio5/www/site/mage2local/pestle.phar/modules/pulsestorm/magento2/cli/generate/observer/module.php:35
PHP   7. ReflectionFunction->invokeArgs() /tmp/pestle_cache/2d27f575ea4837c003f8467c72c32131/reflection-strategy/baf3662faf17339378692b6967fc8c4d.php:7
PHP   8. Pulsestorm\Magento2\Cli\Library\initilizeModuleConfig() /tmp/pestle_cache/2d27f575ea4837c003f8467c72c32131/reflection-strategy/baf3662faf17339378692b6967fc8c4d.php:7

**Comment by astorm** [comment]
@dio5 Hmmm, I"m not seeing this one either.   Could you do two things to help me debug this remotely?
1. Could you paste the contents of `md5 /path/to/your/pestle.phar` here?
2. Remove the pestle namespace/module cache folder at `/tmp/pestle_cache` (should happen automatically, but if there's a bug there Bad Things can happen) and let me know if the problems persist
3. If the above doesn't help -- try re-downloading the phar? `curl -LO http://pestle.pulsestorm.net/pestle.phar`

Re: #3 -- I just downloaded the latest version of the phar and didn't see the same issues you're seeing.  A re-download would be a nice sanity check that could fix the problem, or will let us move on to the next stage of debugging.

**Comment by dio5** [comment]
Sorry, this is fixed as well. Apparently the second time I upgraded I got the link from the wiki 

curl -LO http://alanstorm.com/2016/projects/pestle/pestle.phar
which breaks it.

While this one works:
curl -LO http://pestle.pulsestorm.net/pestle.phar

**Comment by astorm** [comment]
Wiki's updated with the right link.  I was originally distributing via my personal site before I decided the phar needed a real home.
