### ISSUE TITLE
Syntax error with current build

### ISSUE THREAD

**Issue by twosg** [astorm/pestle#138]
I wanted to try out pestle which seems to be a great idea.

However with the built build or when i build myself with ./build.sh I get the error:

PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \ (T_NS_SEPARATOR) in phar:///home/sven/PROJEKTE/Magento_Extensions/pestle/pestle/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 8
PHP Stack trace:
PHP   1. {main}() /home/sven/PROJEKTE/Magento_Extensions/pestle/pestle/pestle.phar:0
PHP   2. main() /home/sven/PROJEKTE/Magento_Extensions/pestle/pestle/pestle.phar:9

**Comment by astorm** [comment]
@twosg are you running PHP 5.6 or greater? (`php -v` from the command line if you're not sure)

**Comment by twosg** [comment]
@astorm no I am using 5.5.9 currently. Should I update in order to run pestle?

**Comment by astorm** [comment]
@twosg Ah, that'll do it.  Pestle requires PHP 5.6 or greater.  One of its non-magento goals was/is to implement a better version of namespace/moduled **functions**, so we require the PHP `use function` syntax that's **only** available in PHP 5.6+

Sorry for the ugly break -- we've got an issue open to do a version check and return a better error message in the future. https://github.com/astorm/pestle/issues/139

**Comment by twosg** [comment]
@astorm Thanks it works now :)
