### ISSUE TITLE
PHP Fatal error:  Cannot redeclare Class

### ISSUE THREAD

**Issue by weilunallen** [astorm/pestle#151]
I accidentally install pestle on my home directory, instead of magento root, and I get the following error from the php log. 

`PHP Fatal error:  Cannot redeclare Pulsestorm\Magento2\Cli\List_Commands\pestle_cli() (previously declared in phar:///Applications/MAMP/htdocs/magento2/pestle.phar/modules/pulsestorm/magento2/cli/list_commands/module.php:16) in phar:///Users/webDesign/pestle.phar/modules/pulsestorm/magento2/cli/list_commands/module.php on line 60` 

I try to remove the 1st .phar, and restart the server/computer but the problem persist, any ideas on how to fix it?

**Comment by astorm** [comment]
@weilunallen What version of PHP are you using? (`php -v`)

Also, try deleting the `/tmp/pestle_cache` folder.

**Comment by weilunallen** [comment]
clearing cache helped! thanks.

**Comment by astorm** [comment]
Got it, closing this out -- @weilunallen, if you're still having trouble let us know!
