### ISSUE TITLE
Getting PHP Parse error:  syntax error

### ISSUE THREAD

**Issue by wclsandipan** [astorm/pestle#160]
Getting parse error while trying to use pestle.
curl -LO http://pestle.pulsestorm.net/pestle.phar
php pestle.phar list
PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \ (T_NS_SEPARATOR) in phar:///var/www/html/magento/magento205ce/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 8

Please help.

**Comment by wclsandipan** [comment]
Hello Alan,

It is working once I upgrade php from 5.5.9 to 5.6.22.
Thanks.

**Comment by astorm** [comment]
Glad you got it solved!
