### ISSUE TITLE
unexpected 'function' (T_FUNCTION)

### ISSUE THREAD

**Issue by anybao** [astorm/pestle#161]
Sorry, i got this issue when trying to use Pestle
`PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in phar:///var/www/magento2s/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 8`

**Comment by astorm** [comment]
@anybao Pestle requires PHP 5.6 or greater.  If you're running with PHP 5.6, please reopen and let us know so we can investigate further!

Thanks for giving pestle a try.
