### ISSUE TITLE
 Showing Warning When Create New Module

### ISSUE THREAD

**Issue by bhavin88** [astorm/pestle#164]
$ c:/xampp/php/php pestle.phar generate_module
Vendor Namespace? (Pulsestorm)] PHP Warning:  Missing argument 1 for Pulsestorm\
Pestle\Library\inputRawPhp(), called in phar://C:/xampp/htdocs/magento_207/pestl
e.phar/modules/pulsestorm/pestle/library/module.php on line 172 and defined in p
har://C:/xampp/htdocs/magento_207/pestle.phar/modules/pulsestorm/pestle/library/
module.php on line 154

Warning: Missing argument 1 for Pulsestorm\Pestle\Library\inputRawPhp(), called
in phar://C:/xampp/htdocs/magento_207/pestle.phar/modules/pulsestorm/pestle/libr
ary/module.php on line 172 and defined in phar://C:/xampp/htdocs/magento_207/pes
tle.phar/modules/pulsestorm/pestle/library/module.php on line 154

Module Name? (Testbed)] PHP Warning:  Missing argument 1 for Pulsestorm\Pestle\L
ibrary\inputRawPhp(), called in phar://C:/xampp/htdocs/magento_207/pestle.phar/m
odules/pulsestorm/pestle/library/module.php on line 172 and defined in phar://C:
/xampp/htdocs/magento_207/pestle.phar/modules/pulsestorm/pestle/library/module.p
hp on line 154

Warning: Missing argument 1 for Pulsestorm\Pestle\Library\inputRawPhp(), called
in phar://C:/xampp/htdocs/magento_207/pestle.phar/modules/pulsestorm/pestle/libr
ary/module.php on line 172 and defined in phar://C:/xampp/htdocs/magento_207/pes
tle.phar/modules/pulsestorm/pestle/library/module.php on line 154

Version? (0.0.1)] PHP Warning:  Missing argument 1 for Pulsestorm\Pestle\Library
\inputRawPhp(), called in phar://C:/xampp/htdocs/magento_207/pestle.phar/modules
/pulsestorm/pestle/library/module.php on line 172 and defined in phar://C:/xampp
/htdocs/magento_207/pestle.phar/modules/pulsestorm/pestle/library/module.php on
line 154

Warning: Missing argument 1 for Pulsestorm\Pestle\Library\inputRawPhp(), called
in phar://C:/xampp/htdocs/magento_207/pestle.phar/modules/pulsestorm/pestle/libr
ary/module.php on line 172 and defined in phar://C:/xampp/htdocs/magento_207/pes
tle.phar/modules/pulsestorm/pestle/library/module.php on line 154

Created: C:\xampp\htdocs\magento_207/app/code/Pulsestorm/Testbed/etc/module.xml
Created: C:\xampp\htdocs\magento_207/app/code/Pulsestorm/Testbed/registration.php

**Comment by astorm** [comment]
@bhavin88 Thank you, this one's a straight up bug!  We've pushed a fix and uploaded a new version of the extension,  Could you give it a try and let us know if you're still seeing this problem?

https://github.com/astorm/pestle/issues/164

**Comment by bhavin88** [comment]
Now it is working fine. Thank you.
