### ISSUE TITLE
Can't find [VendorName] in Pulsestorm\Pestle\Runner\includeLibraryForCommand

### ISSUE THREAD

**Issue by triple486** [astorm/pestle#170]
Making new test modules under VendorName(Pulsestorm) worked well so far.

I tried to make a new module with a different vendor name(folder) for a test in CLI.
Got an error message from pestle as below:
Can't find [VendorName] in Pulsestorm\Pestle\Runner\includeLibraryForCommand

signed up for a new github account, but still no luck finding any answer or documentation.
Not sure I'm not authorized to read the documentation or it just doesn't exist at all.

Can someone help me finding answer for this please?

**Comment by astorm** [comment]
@triple486 Can you let us know 
1. Where the file was created?
2. What the context of the file were?

With that we can help you diagnose the problem.  The exact "how to create a new command/module" is a still little mushy/freeform.  Part of the tradeoffs in building a new system from scratch :)

**Comment by triple486** [comment]
1. Tried to create with pestle generate_module command in ordinary path which is root folder/app/code/NewVendorName

This is what I exactly put in shell in CLI.

```
php pestle.phar KT practice 0.0.1
```

and then, it returned this.

> Can't find [KT] in Pulsestorm\Pestle\Runner\includeLibraryForCommand

I also tried after making a new vendor directory manually, but still returned same error message.

Am I supposed to add a new vendor name through some pestle command something like pestle_import? (just assumed with a research)

Thought there should be an easy way since adding a new vendor name is very basic and important to get full use of pestle... otherwise, we all have to put every pestle generated module under 'Pulsestorm' vendor name.... :(
1. can't tell what the context of the file was because it was only for practice and it failed in very first step.

**Comment by astorm** [comment]
@triple486 OK, got it.  Are you trying to use pestle to create a module on your Magento 2 system? Or are you trying to create a new pestle command?  The rest of this assumes the former, not the later.

It looks like you're missing the pestle command you want to run

```
pestle.phar KT practice 0.0.1
```

vs. 

```
pestle.phar generate_module KT practice 0.0.1
```

Can you let us know where you found the `pestle.phar KT practice 0.0.1` code sample?  We'd like to correct it.   Also, re: docs, there are some in the wiki

https://github.com/astorm/pestle/wiki

And lots of usage example in this article series

http://alanstorm.com/category/magento-2#magento_2_mvc

Does that straighten you out?  Or do you need more help?

**Comment by triple486** [comment]
Oh.. haha
So, it was my mistake forgot to put generate_module command :p
I retried with proper command now it worked.

Thank you!!

Not sure if I have to open it up as a new issue or ask here but just one more thing..

My downloaded pestle.phar file is in the root of magento folder.
I have to type php in front of pestle.phar command every time to make it work.

bin/magento command works without anything in front of it, by the way.

Is there any specific folder that I have to put pestle.phar file for pestle command to work without php in front?

**Comment by astorm** [comment]
@triple486 That's less a specific project thing and more of general unix thing.  Happy to provide some help though.

The reason you can `bin/magento` without the `php` command line is `bin/magento` has it's "executable" permission set.  This tells the underlying operating system that users would be able to run the file `magento` as a command. 

You can give any file on your system the executable permission with the following

```
chmod +x path/to/file
```

Once you've done that, you can run the file as a program.  This means if you were in your Magento root folder, you could run pestle with

```
./pestle.phar
```

or if you put it in Magento's `bin` folder, you could run it with 

```
bin/pestle.phar
```

If you wanted to be able to run pestle **anywhere**, you'd need to put the `pestle.phar` file somewhere in your unix path.  The two most common places for this is 

```
~/bin/pestle.phar  //(your home folder's bin)
/usr/local/bin/pestle.phar  (the system's local bin, traditionally reserved for non-system executables)
```

However, depending on your unix, and how its setup, you may need to add these folders to your unix `$PATH` yourself.  We'll leave that as an exercise for the reader, but feel free to ask for more help if you need. it.

**Comment by triple486** [comment]
Awesome, putting it in Magento's bin folder sounds fit for my need.
Pestle helps me to save tons of hassle making/testing new modules.
Thank you so much!

**Comment by astorm** [comment]
@triple486 Happy to help!
