### ISSUE TITLE
Extending existing menu.xml instead of overwriting it

### ISSUE THREAD

**Issue by grasdaggel** [astorm/pestle#172]
When using `php pestle.phar generate_menu`, pestle should check for the existence of a menu.xml in the modules files. If theres a menu, check for first `<menu>` item and extend it, rather then completly overwriting the file thus removing the developers settings before.

**Comment by grasdaggel** [comment]
I'm sorry - pestle already does this.

What happens instead is, that the formatting of the file gets lost. Pestle removes tabs and \r\n's out of the file. Pestle right now does NOT overwrite existing settings. My fault!

**Comment by astorm** [comment]
Thanks for the feedback @grasdaggel -- I couldn't reproduce this problem -- could you try downloading the latest version of pestle and trying again?  If the problem persists, could you 
1. Provide an example of a menu.xml file with formatting
2. Provide example inputs from running `php pestle.phar generate_menu`
3. Provide an example of a menu.xml file after running the command, with the lost formatting. 

If you could zip up the two `menu.xml` file that would be ideal.   With that information we should be able to get to the bottom of this!

**Comment by astorm** [comment]
@grasdaggel any update on the above request?  Or are you good here?

**Comment by grasdaggel** [comment]
Sorry for not coming back at you, I'm good! Thanks Alan!

**Comment by astorm** [comment]
Thanks @grasdaggel !
