### ISSUE TITLE
Should command names have underscores, or dashes?

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#206]
pestle.phar magento2:generate:ui:add-column-actions

vs.

    pestle.phar magento2:generate:controller_edit_acl

**Comment by navarr** [comment]
My opinion: dashes.  

I'm unfamiliar with the layout of other locales, but an en_US-qwerty keyboard requires shift for _ but not for -.  - is the easier to type glyph in that case.

**Comment by timbroder** [comment]
My opinion: -

**Comment by sambolek** [comment]
As dashes don't require modifier key to use, I prefer dashes.

Underscores make more sense to me for class paths, as paths are written with capitals to separate folders, so shift key is already pressed in preparation for next capital letter.

**Comment by astorm** [comment]
Thanks all -- poll come out to be 70% in favor of dashes.  For pestle the `pestle:generate_command` command will default to generating commands with dashes, but internally we'll normalize the command names so those already with underscores (like `pestle:generate_command` itself) are interpreted as (`pestle:generate-command`).  This will let the other 30% do what they want without too much trauma.

**Comment by astorm** [comment]
OK, dash/underscore interchangeableness happened here

https://github.com/astorm/pestle/commit/106c0c484a4a5c79c23c7965efafb1b73a2f3bb1

**Comment by astorm** [comment]
Alright, we've converted all the `_` command names to `-` command names, but old underscore names will still be recgonized.  One downside of our approach is something like `pulsestorm:md_to-say` -- a command that mixes dashes and underscores is not supported.  I'm OK with that weirdness not being possible, but have opened a new issue for adding a warning if that situation comes up.

https://github.com/astorm/pestle/issues/217
