### ISSUE TITLE
Typo's

### ISSUE THREAD

**Issue by peterjaap** [astorm/pestle#208]
`  php:test_namespace_integrity               ALPHA: Tests the "namepace integrity?  Not sure what this is anymore.`
namepace -> namespace

When running `pestle.phar magento2:scan:class_and_namespace app/code`;
`No Namspace: Skipping app/code/Client/OrderSync/Model/Esb/PushOrder.php`
Namspace > Namespace

`  magento2:convert_observers_xml             ALPHA: Partiall converts Magento 1 config.xml to Magento 2`
Partiall > Partially

**Comment by astorm** [comment]
Thanks @peterjaap -- fixed, and should be part of next week's release.
