### ISSUE TITLE
Observers created in Model as opposed to 'Observer'

### ISSUE THREAD

**Issue by QwertyZW** [astorm/pestle#234]
according to this article http://devdocs.magento.com/guides/v2.0/extension-dev-guide/events-and-observers.html observers may be placed under <my_vendor>/<my_module>/Observer instead of <my_vendor>/<my_module>/Model which is pestle's current fallback-to directory

Btw Alan great professional weblog and pestle is awesome 🥇

**Comment by astorm** [comment]
Thanks @QwertyZW, good catch.  Those naming conventions were still shaking out when we created the command.  It looks like the core follows that particular bit of dev docs advice so it makes sense for pestle to do the same.

Example of the new default class name is here

    $ pestle_dev magento2:generate:observer
    Full Module Name? (Pulsestorm_Generate)] 
    Event Name? (controller_action_predispatch)] 
    Observer Name? (pulsestorm_generate_listener)] 
    Class Name? (Pulsestorm\Generate\Observer\Listener)] ^C

The last argument uses the module name, plus (the observer name minus any module name parts) to generate a new class name.  Users can still input whatever they want.  i.e.

    //combine the two
    Pulsestorm_Generate pulsestorm_generate_listener
    //all the words
    Pulsestorm Generate Pulsestorm Generate Listener
    //module words removed from observer words 
    Pulsestorm Generate Listener
    //Class name by inserting Observer
    Pulsestorm Generate Observer Listener
    Pulsestorm\Generate\Observer\Listener

This issue also revealed the `* @argument model_name @callback getModelName` handlers only received non-default arguments.  We've fixed that here as well by adding a third parameter that should pass the callback method the actual entered argument OR the default.  

This is available now in the master branch, will go live with the next pestle point release. 

Please reopen if we missed some nuance of what you were after!
