### ISSUE TITLE
generate:ui:add-schema-column   Undefined class constant 'PS_TYPE_VARCHAR'

### ISSUE THREAD

**Issue by ddoddsr** [astorm/pestle#262]
This are my pestle commands on a clean M2:
pestle.phar magento2:generate:module Foredev Hellotest 0.0.1
pestle.phar generate_crud_model Foredev_Hellotest Thing
pestle.phar magento2:generate:ui:add-schema-column app/code/Foredev/Hellotest/Setup/InstallSchema.php foredev_hellotest_thing thing_name varchar

bin/magento module:enable Foredev_Hellotest
The following modules have been enabled:
- Foredev_Hellotest

bin/magento setup:upgrade
...
Updating modules:
Schema creation/updates:
Module 'Foredev_Hellotest':
Installing schema... PHP Fatal error:  Undefined class constant 'PS_TYPE_VARCHAR' in /Users/dandodd/Projects/tpmco.dev/app/code/Foredev/Hellotest/Setup/InstallSchema.php on line 46

Fatal error: Undefined class constant 'PS_TYPE_VARCHAR' in /Users/dandodd/Projects/tpmco.dev/app/code/Foredev/Hellotest/Setup/InstallSchema.php on line 46

**Comment by astorm** [comment]
Confirmed.  The PS_ prefix was meant for as an internal to pestle thing for the various text types.  Looks like it accidentally leaked though into the generated file.  We're investigating and preparing a patch release.  In the meantime, you can continue by manually editing InstallSchema.php and changing `PS_TYPE_VARCHAR` to `TYPE_TEXT`.

**Comment by ddoddsr** [comment]
That FIxed the VARCHAR, now I get the warning in the decimal:
```
 [Exception]                                                                                                                               
  Warning: array_key_exists() expects parameter 2 to be array, integer given in /Users/dandodd/Projects/tpmco.dev/vendor/magento/framework  
  /DB/Ddl/Table.php on line 352
``` 
 ->addColumn('thing_count',
            \Magento\Framework\DB\Ddl\Table::TYPE_DECIMAL,
Is ---->>    12,4,
S/B -->>  [12,4]
            ['nullable' => false, 'default' => '0.0000'],
            "thing_count field"
        )

Thanks

**Comment by astorm** [comment]
That @ddoddsr -- have any other problems cropped up as you've used the new command?

**Comment by ddoddsr** [comment]
I'll let you know as I find them, least I can do to help out on a cool tool.
I'll work on some more this weekend.

I noticed the generate full module left off magento2: on
generate_crud_model, generate_route and generate_view
They did work as far as I can tell

**Comment by astorm** [comment]
Thanks again @ddoddsr -- we just pushed pestle 1.3.1 to the servers. The version should fix the problem with PS_ constants as well as the missing array brackets for the decimal type.

Re: generate_crud_model, generate_route -- those were the original command names before we moves to the magento2:generate:etc... style names.  There's a informal aliasing system in place that allows the old generate_crud_model, generate_route style commands to keep working for folks who are reading old documentation. 

That should cover things -- if you're still having trouble, or find more problems, please feel free to reopen this issue or open a new one.  Thanks again for your bug reports -- pestle wouldn't be possible without them.
