### ISSUE TITLE
Crud Model -- Do we need to generate Factories? If not, stop it.

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#281]
Pulsestorm\ToDoCrud\Model\TodoItemFactory

Are we generating a source file for this class?  Do we need to?  Should the generation code rely on auto generated factories?

**Comment by Vinai** [comment]
I think it would be best to rely on the Magento 2 code generation for factories, since that is how the core is intended to be used and I don't see any real benefit of generating them inside the module.  
In fact, a module containing factories would for me violate the principle of least surprise :)

**Comment by astorm** [comment]
Hmmm -- I see to have lost the context on this one as the current pestle code is **not** generating any factories directly, and I generally agree with @Vinai :)  Closing out -- if I'm missing something obvious please reopen and let me know.
