### ISSUE TITLE
Feature request: Generate classes with magento DI boilerplate 

### ISSUE THREAD

**Issue by QwertyZW** [astorm/pestle#283]
One common thing we do in almost all magento 2 php file is:

1) Declare an argument  in a constructor
2) Declare a property within a class
3) Assign injected dependency to the class property

;I.e the dependency injection dance

I think the challenge here is figuring out an ideal method with which we can let pestle know that we'd like certain dependencies to be injected in certain generated classes. The reason why I think this is a challenge is because I think the ui (here the commandline) can quickly get confusing for commands that generate multiple php files. This might not be true though, this is just an opinion.

A feature like this opens doors for constructor parameter validation in the future.

**Comment by astorm** [comment]
Hmmm, I have vague memories that there's an old `generate-di` (hidden from help, but should still be active) that did something like this.  Might be worth investigating. Can't remember why this didn't make the cut when we moved to `magento2:...` style names

    $ pestle_dev generate-di

**Comment by QwertyZW** [comment]
This is actually pretty neat; why wouldn't it have made it through is a good question.

With a bit of work on autocompleteing magento namespaces as arugements we will be all set.

**Comment by QwertyZW** [comment]
I see the command is now listed under the `list` command, I think this issue can be closed?

**Comment by astorm** [comment]
Ha, so it is -- under `magento2:generate:di`, yes?  I forgot about adding this to the repository.  *this is not the professional release management you're looking for*.  

Closing out, but if there's future issues please feel free to reopen.

**Comment by QwertyZW** [comment]
Yep

```
khishman@khishman-desktop:~$ ~/magento2/pestle/pestle_dev list | grep "generate:di"
  magento2:generate:di                       Injects a dependency into a class constructor
khishman@khishman-desktop:~$ 
```

Thanks!

**Comment by QwertyZW** [comment]
@astorm I think the reason why it might not have been included is because `...generate:di` may also cause the user to think that it implies 'add a di instruction to di.xml' such as a preference node

**Comment by astorm** [comment]
@QwertyZW That might be it -- how does 

    magento2:generate:di:param

sound?

**Comment by QwertyZW** [comment]
I would have suggested to keep the `:` as a seperator between `<platform>:<action>:<target>` but it looks like we have `magento2:generate:ui:* ` so it should be alright
