### ISSUE TITLE
Missing use SortOrder in CRUD's ModelRepository

### ISSUE THREAD

**Issue by Dublerq** [astorm/pestle#304]
Hi Alan,
first of all I need to thank you for great work on this tool. Really saves a lot of time. Unfortunately I found a small bug in CRUD generator.

In `getList()` method there is $sortOrder->getDirection() comparison with SortOrder::SORT_ASC. That class is undefined.

It can be fixed by generating an extra use:
```
use Magento\Framework\Api\SortOrder;
```
At the top of class. 

If I may suggest one more feature to add I would really like to see in CRUD a generation of interface preferences that is for instance:
```
<preference for="Training\Test2\Api\Example2RepositoryInterface" type="Training\Test2\Model\Example2Repository"/>
<preference for="Training\Test2\Api\Data\Example2Interface" type="Training\Test2\Model\Example2"/>
```
 Kindest regards!

**Comment by Dublerq** [comment]
Fix of the issue in Pull Request https://github.com/astorm/pestle/pull/305

**Comment by astorm** [comment]
Thank you @Dublerq, we'll take a look at this pull request today or tommorrow!

Quick question -- which version of Magento 2 were you using when you saw the raised error? 2.0, 2.1, or 2.2?

**Comment by Dublerq** [comment]
It was fresh Magento 2.1.8 CE on Ubuntu 16.04 with PHP7-FPM

**Comment by astorm** [comment]
Thanks agin @Dublerq -- pull request accepted, new issue opened for the interface request. Closing this one out, but feel free to reopen if there's still something that needs addressing. 

https://github.com/astorm/pestle/issues/306
