### ISSUE TITLE
Improve magento2:generate:schema-upgrade command.

### ISSUE THREAD

**Issue by davidangel** [astorm/pestle#312]
It would be nice to be able to access the object manager from within the generated migration files. This would allow for nice injection of helpful libraries for installing or changing data.

Example:
![image](https://user-images.githubusercontent.com/1071952/31772705-84dc54e4-b4ae-11e7-9bd9-d9c74e1e90b9.png)

Would you be open to a PR for pestle that includes this injection in the generated classes? Or are there reasons this could be a bad idea?

**Comment by astorm** [comment]
@davidangel I can see the utility of this but -- Magento itself recommends that folks not directly use the object manager (even though they can't stick to this rule themselves) so I'd be wary of offering it as an option in these setup classes.  If folks want to have an object manager, they can/should add it to their own classes. 

That said -- these classes still go through automatic constructor dependency injection, which means you can inject dependencies in the constructor.  If you're sick of that boilerplate, checkout the 

    pestle.phar magento2:generate:di

command.  This will automatically inject a dependency into any class file for you. 

Closing this out, but thank you for the suggestion.
