### ISSUE TITLE
the generate view command should create correct xml file content

### ISSUE THREAD

**Issue by jerome-zhang** [astorm/pestle#313]
when you run generate view command, it should create xml file with <referenceContainer name="content"> instead of <referenceBlock name="content">

**Comment by astorm** [comment]
Thank you for your feedback!

@jerome-zhang Could you clarify what you mean?  

> it should create xml file with instead of

The above is not clear.  Is it missing some text?

**Comment by jerome-zhang** [comment]
when you run generate view command, it should create page configuration xml file with
`<referenceContainer name="content">`
instead of 
`<referenceBlock name="content">`

**Comment by astorm** [comment]
yes it should!  Fix made in https://github.com/astorm/pestle/pull/314 and will land in the next release.  Closing out for now, but reopen if you're still having trouble.
