### ISSUE TITLE
Is Cached Magento Basedir Per Magento Instance?

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#320]
It sounds like there may be Magento basedir and/or base pestle dir problems when switching between projects?

    sven@SG-MINT18 ~/PROJEKTE/Domains/domain-magento2 $ php pestle.phar 
    PHP Warning:  require_once(phar:///home/sven/PROJEKTE/Domains/domain.de-m2/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php): failed to open stream: phar error: invalid url or non-existent phar "phar:///home/sven/PROJEKTE/Domains/domain.de-m2/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php" in phar:///home/sven/PROJEKTE/Domains/domain-magento2/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 136
    PHP Fatal error:  require_once(): Failed opening required 'phar:///home/sven/PROJEKTE/Domains/domain.de-m2/pestle.phar/modules/pulsestorm/magento2/cli/help/module.php' (include_path='phar:///home/sven/PROJEKTE/Domains/domain-magento2/pestle.phar/vendor/phing/phing/classes:.:/usr/share/php') in phar:///home/sven/PROJEKTE/Domains/domain-magento2/pestle.phar/modules/pulsestorm/pestle/runner/module.php on line 136

Per https://github.com/astorm/pestle/issues/120#issuecomment-348811249

**Comment by astorm** [comment]
@twosg when you saw the above errors -- where had you gotten the `phar` file from?  Was it something you downloaded?  Or something you built yourself?

**Comment by twosg** [comment]
@astorm I used `curl -LO http://pestle.pulsestorm.net/pestle.phar` to get the phar.

**Comment by astorm** [comment]
Did some testing, and the answer to 

> Is Cached Magento Basedir Per Magento Instance

seems to be -- No.  Closing out, but if anyone finds evidence that run contrary to this, please don't hesitate to update things here or open a new issue.
