### ISSUE TITLE
Use SemVer'd faker library

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#321]
Per: https://github.com/astorm/pestle/issues/120#issuecomment-348811249

    sven@SG-MINT18 ~/project-dir $ composer require pulsestorm/pestle
    Using version ^1.4 for pulsestorm/pestle
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - Installation request for fzaninotto/faker == 1.7.1.0 -> satisfiable by fzaninotto/faker[v1.7.1].
        - pulsestorm/pestle 1.4.0 requires fzaninotto/faker 1.6.0 -> satisfiable by fzaninotto/faker[v1.6.0].
        - pulsestorm/pestle 1.4.1 requires fzaninotto/faker 1.6.0 -> satisfiable by fzaninotto/faker[v1.6.0].
        - pulsestorm/pestle 1.4.2 requires fzaninotto/faker 1.6.0 -> satisfiable by fzaninotto/faker[v1.6.0].
        - Conclusion: don't install fzaninotto/faker v1.6.0
        - Installation request for pulsestorm/pestle ^1.4 -> satisfiable by pulsestorm/pestle[1.4.0, 1.4.1, 1.4.2].
    Installation failed, reverting ./composer.json to its original content.

**Comment by astorm** [comment]
@twosg Was this a Magento project you were trying to add `pulsestorm/pestle` to?  Or some other random PHP project.  Regardless of that -- do you know what the semantic version string from your composer.json file looked like for `fzaninotto/faker`?

**Comment by twosg** [comment]
@astorm Yes it is a Magento project.

That is the composer.json:
```
{
    "name": "magento/project-community-edition",
    "description": "eCommerce Platform for Growth (Community Edition)",
    "type": "project",
    "version": "2.0.2",
    "repositories": [
        {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    ],
    "require": {
        "magento/product-community-edition": "2.2.1",
        "composer/composer": "@alpha",
        "n98/magerun2": "^2.0",
        "staempfli/magento2-code-generator": "^1.8"
    },
    "require-dev": {
        "phpunit/phpunit": "4.1.0",
        "squizlabs/php_codesniffer": "1.5.3",
        "phpmd/phpmd": "@stable",
        "pdepend/pdepend": "2.0.6",
        "sjparkinson/static-review": "~4.1",
        "fabpot/php-cs-fixer": "~1.2",
        "lusitanian/oauth": "~0.3 <=0.7.0"
    },
    "config": {
        "use-include-path": true
    },
    "autoload": {
        "psr-4": {
            "Magento\\Framework\\": "lib/internal/Magento/Framework/",
            "Magento\\Setup\\": "setup/src/Magento/Setup/",
            "Magento\\": "app/code/Magento/"
        },
        "psr-0": {
            "": "app/code/"
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Magento\\Sniffs\\": "dev/tests/static/framework/Magento/Sniffs/",
            "Magento\\Tools\\": "dev/tools/Magento/Tools/",
            "Magento\\Tools\\Sanity\\": "dev/build/publication/sanity/Magento/Tools/Sanity/",
            "Magento\\TestFramework\\Inspection\\": "dev/tests/static/framework/Magento/TestFramework/Inspection/",
            "Magento\\TestFramework\\Utility\\": "dev/tests/static/framework/Magento/TestFramework/Utility/"
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true,
    "extra": {
        "magento-force": "override"
    }
}
```
It is "n98/magerun2": "^2.0" which requires the `fzaninotto/faker` in 1.7.1.0. After removing magerun2, I can require pestle. And after pestle is required, I can also add magerun2 in 2.0.0 version.

So it seems this is just a composer problem and nothing wrong with pestle :)

Thanks for your help!

**Comment by astorm** [comment]
Magerun seems to have [this locked at 1.6.0](https://github.com/netz98/n98-magerun2/blob/develop/composer.lock#L302), so I'm not sure where your 1.6 was coming from.  That, plus your comments, makes me think everything is addressed here.  However, if your'e still having trouble, please don't hesitate to reopen this issue, or open a new and (and apologies for the delay -- being a one man band doesn't always make for the most timely of responses)
