### ISSUE TITLE
Unable to find the wrapper "phar"

### ISSUE THREAD

**Issue by srenon** [astorm/pestle#435]
Magento 2.2.8

$ php pestle.phar magento2:class-list

Warning: require(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /MagePal/magento2ce/lib/internal/Magento/Framework/registration.php on line 14

Warning: require(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in /MagePal/magento2ce/lib/internal/Magento/Framework/registration.php on line 14

Warning: file_get_contents(): Unable to find the wrapper "phar" - did you forget to enable it when you configured PHP? in phar:///MagePal/magento2ce/pestle.phar/modules/pulsestorm/pestle/importer/module.php on line 273

Warning: file_get_contents(phar:///MagePal/pestle.phar/modules/pulsestorm/magento2/cli/class_list/module.php): failed to open stream: No such file or directory in phar:///MagePal/magento2ce/pestle.phar/modules/pulsestorm/pestle/importer/module.php on line 273

Notice: Undefined index: file in phar:///MagePal/magento2ce/pestle.phar/modules/pulsestorm/pestle/importer/module.php on line 407

Warning: file_get_contents(): Filename cannot be empty in phar:///MagePal/magento2ce/pestle.phar/modules/pulsestorm/pestle/importer/module.php on line 273

See
- https://github.com/magento/magento2/issues/21973

**Comment by astorm** [comment]
Maybe Magento will fix this on their end? (lol)

That's super annoying.  We can probably fix it on this side by calling `stream_wrapper_restore('phar');` right after bootstrapping Magento into place -- although I'm not sure what versions of PHP that exists in on what will happen if you you call it multiple times in same.  _sigh_    Fix would go right after this require statement: https://github.com/astorm/pestle/blob/cfd14d3fee341d6e48856a2355546c51ea8a5e60/modules/pulsestorm/magento2/cli/class_list/module.php#L139

I probably won't have time to work on this for a week or so, so if someone else wants to grab it from me and fix it then PR away.

@srenon out of curiosity, what do you use this command for?  Most of the non `generate` pestle commands are one off scripts I wrote quick to do some small task then forgot about.  I'd be curious to know what value you found from the `class-list` command.

**Comment by srenon** [comment]
Thanks for the quick reply! 

I was just testing out Pestle and that was the first command I tried because I was curious to see what it does. But funny enough I had the same exact issue with an older version of n98-magerun2 with preventing all the functions from working. So I assumed the same was true here, but after trying other function they all worked.

**Comment by astorm** [comment]
> So I assumed the same was true here, but after trying other function they all worked.

Yes.  This one command loads up Magento's `app/bootstrap.php` file so it can use the functionality provided by the `Magento\Setup\Module\Di\Code\Reader\ClassesScanner` class to find find all the "extendable" classes.  To be honest I can't remember what, exactly, "extendable" means here :)

While it's possible to use Magneto classes without bootstrapping, you end up needing to manually instantiate everything in any constructor (thanks to Magento's automatic constructor dependency injection), which can be pretty tedious and error prone. 

Other pestle commands don't need to load/bootstrap a Magento environment, so they're fine. 

I [yoinked a fix from @cmuench](https://github.com/netz98/n98-magerun2/commit/59e0aec6097e6e8bed217aa1343d6906bb5fb92c) and [merged it](https://github.com/astorm/pestle/pull/437). 

I'm honestly not sure when this fix will land in a release -- historically we tend to flll up a ["current sprint" milestone](https://github.com/astorm/pestle/milestone/19) with 10 complete issues and then do a release, but development's been slow around here and [the docs sprint](https://github.com/astorm/pestle/milestone/21) is our priority at the moment.  And when I say "we" and "our" [I mean me](https://www.patreon.com/alanstorm) :)  

If anyone's burning to checkout this command with a Magento 2.3.1 system [the README](https://github.com/astorm/pestle#how-to-use) has instructions for using `phing` to do your own build.

@srenon Thanks again for reporting this, and apologies that your first experience with pestle was an error.  ~We~ I hope it doesn't sour you on the command.  We're closing this issue out now, but if you need anything else please feel free to comment/re-open.
