### ISSUE TITLE
Please update Packagist.org

### ISSUE THREAD

**Issue by JeroenBoersma** [astorm/pestle#478]
Packagist.org is out of sync.
Strangely it it isn't updated automaticaly.

https://packagist.org/packages/pulsestorm/pestle

Thanks :-)

**Comment by astorm** [comment]
@JeroenBoersma  Can you let us know which part is out of sync?  i.e. a "I see X here, but its Y there" sort of thing.

**Comment by astorm** [comment]
@JeroenBoersma Can you let us know what part of packagist is out of sync?  We'd love to fix whatever you're seeing -- but we're not seeing it.

**Comment by JeroenBoersma** [comment]
Hi @astorm 

of coarse I can :)

If I take a look here: https://github.com/astorm/pestle/releases it states `1.4.4` as the latest.
And on https://packagist.org/packages/pulsestorm/pestle `1.4.3` is the latest.

cheers :)

**Comment by astorm** [comment]
Hmmm -- that's interesting.  The 1.4.3 release was a hiccup in the build/packaging system here -- basically a phar tagged with 1.4.3 got into the wild without a formal release, so we needed to release a 1.4.4 version immediately.  In github 1.4.3 and 1.4.4 have the same contents -- the tag tags the same commit hash.  I'm guessing this (confusing situation) confuses packagist.  Edge cases all the way down.

So I could probably delete the 1.4.3 tag -- I'm curious if packagist would pickup on that.

@JeroenBoersma While I give this is think, how did you come to notice this issue?  Just eagle eyes, or did it break something?

**Comment by JeroenBoersma** [comment]
Nope, I didn't went into the contents, so I got noticed to update to 1.4.4 and I could't that's all

So we found a glitch, whoop

**Comment by JeroenBoersma** [comment]
I'll close this, it'll be resolved in a next version bump too...
