### ISSUE TITLE
Bash Autocomplete

### ISSUE THREAD

**Issue by astorm** [astorm/pestle#57]
I have no idea how to do this.

**Comment by astorm** [comment]
Colon character is causing problems.

```complete -W "magento2\:fix-permissions-modphp" pestle.phar```

Possible work arounds

http://stackoverflow.com/questions/25362968/bash-command-line-tab-completion-colon-character

http://stackoverflow.com/questions/2805412/bash-completion-for-maven-escapes-colon/12495727#12495727

**Comment by astorm** [comment]
https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/composer/composer.plugin.zsh

**Comment by astorm** [comment]
Saving some useful comments here

    _pestleAutocomplete ()
    {
        local cur
        #cur=${COMP_WORDS[COMP_CWORD]}
        _get_comp_words_by_ref -n : cur
        #echo $cur
        #"'@><=;|&(:
        #_get_comp_words_by_ref -n : cur
        # echo ""
        #echo $cur
        # echo ""
        all=$(_commandList)
        COMPREPLY=( $(compgen -W "$all" $cur) )
        __ltrim_colon_completions "$cur"
        #COMPREPLY=()    
        #COMPREPLY=("Goodbye")
        return 0
    }

**Comment by astorm** [comment]
Alright, we have a basic auto complete script.  Refinements will happen here

https://github.com/astorm/pestle/issues/254

To use this you'll need to install the [`bash-completion`](https://github.com/scop/bash-completion) project on your computer.  The built-in completion doesn't have mechanisms for handling our:colon:words and I'm not enough of a bash programmer to figure that out quickly.  Just drop the [pestle-autocomplete.sh](https://github.com/astorm/pestle/blob/master/pestle-autocomplete.sh) script in your `/usr/local/etc/bash_completion.d` (or system equivalent folder) and you'll get the tab completion for command names. Leaving the instructions deliberaly vague here, as there's still some [weird behavior](https://github.com/astorm/pestle/issues/254) I don't want to subject non-power-users to.

**Comment by bnymn** [comment]
I don't understand how it is working? I am writing peste, and pres [TAB] for auto complete, but it does not complete anything.
